### ISSUE TITLE
Improving Docs and description

### ISSUE THREAD

**Issue by art1373** [iran-react-community/elegant-react-native#51]
Personally as a developer I find this part of the docs confusing. If someone is a semi-newbie it will be even cumbersome to read and understand what kind of info this part is trying to transfer.
I like to improve this in a pr
```
yarn
nano app.json /* here we go to edit project name and displayName */
react-native eject /* generate ios and android folders */
react-native link /* add app/assets/fonts and react-native-vector-icons  */
cd ios && pod install && cd ../ && yarn ios
yarn android /* android */
```

**Comment by ramyareye** [comment]
this is cool @art1373 
let's do it \m/
