### ISSUE TITLE
Whats elegant-react-native?

### ISSUE THREAD

**Issue by cinaaaa** [iran-react-community/elegant-react-native#55]
Hi, Guys.
I see this repo needs some contributer.
i want to contribute, but whats elegant-react-native?
whats the purpose of this repo? what issue we solve? what we do ?
please update readme with description of this repo that contains critical informations about this repo.
thanks, regards.

**Comment by ramyareye** [comment]
Hi @E-RROR  ,
I started package to reach a standard structure/boilerplate to init a react-native project.
Main goal is defining common patterns and use community supported libraries to handle what we need. Currently we are publishing our startup app based on this structure and afterward we will apply our changes here.
If you're interested on contribution you can start with any items on Todo list in Readme (included docs :D)

Good day

**Comment by amerllica** [comment]
@E-RROR, If you are not familiar with `issues` please consider here is not for objection, If you think there is a lack in this repo, any kind of lack, and you care about it. you can **fork**, make changes, and send **PR**.

If you think the repo that we are contributing is useless or doesn't solve any problems, you can just leave it alone.
